# **Chi-Square test**

## **Why is chi-square test used for?**
The chi-square test is used to determine whether there is a significant association between two categorical variables. It
is used to test the null hypothesis that there is no association between the variables.

In [3]:
!pip install scipy      # library for different statistical tests.

Requirement already satisfied: scipy in c:\programdata\miniconda3\envs\py_eda\lib\site-packages (1.15.2)
Requirement already satisfied: numpy<2.5,>=1.23.5 in c:\programdata\miniconda3\envs\py_eda\lib\site-packages (from scipy) (2.2.3)

In [5]:
# import the neessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats

In [6]:
# load the titanic built-in dataset
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### **Define the Hypothesis of Chi-Square Test.**
**Null Hypothesis (H0**): There is no association between the gender(`sex`) & survial (`survived`) on the Titanic.

**Alternative Hypothesis (H1)**: There is a association between the gender(`sex`) & survial (`survived`) on the Titanic.

In [8]:
# Perform the chi-square test

# Contingency table
contingency_table = pd.crosstab(titanic['survived'], titanic['sex'])
contingency_table

sex       female  male
survived
0             81   468
1            233   109

In [9]:
# Chi-square test
chi2, p, dof, expected = stats.chi2_contingency(contingency_table)
print(f'Chi-square value: {chi2}')
print(f'p-value: {p}')
print(f'Degrees of freedom: {dof}')
print(f'Expected frequencies: {expected}')

Chi-square value: 260.71702016732104
p-value: 1.1973570627755645e-58
Degrees of freedom: 1
Expected frequencies: [[193.47474747 355.52525253]
 [120.52525253 221.47474747]]

#### We reject the null hypothesis, because the p-value (1.1973570627755645e-58) is very less than 0.05.